name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 0.4.0
homepage: https://acmesoftware.com/
repository: https://github.com/MattHamburger/clean_framework

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  equatable: ^2.0.0-nullsafety.3
  http: ^0.13.0
  provider: ^5.0.0-nullsafety.3

dev_dependencies:
  test: ^1.16.2
  mockito: ^5.0.0-nullsafety.7

